from smolagents import tool
import requests
import os


@tool
def post_to_teams(article: str, title: str = "Weekly AI + SAP Tech Digest") -> str:
    """
    Posts a formatted article to a Microsoft Teams channel via Incoming Webhook
    using a rich Adaptive Card layout.
    Args:
        article: The full article text to post
        title: The title/heading of the Teams message card
    """
    webhook_url = os.getenv("TEAMS_WEBHOOK_URL")
    if not webhook_url:
        return "Error: TEAMS_WEBHOOK_URL not set in environment variables."

    # Split article into sections for better Teams formatting
    # Truncate if too long — Teams Adaptive Cards have a ~28KB limit
    max_length = 20000
    if len(article) > max_length:
        article = article[:max_length] + "\n\n... [Full article saved locally]"

    # Build Adaptive Card with rich formatting
    payload = {
        "type": "message",
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "body": [
                        # Header block
                        {
                            "type": "Container",
                            "style": "emphasis",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "📰 SAP × AI Weekly Enterprise Brief",
                                    "weight": "Bolder",
                                    "size": "Small",
                                    "color": "Accent",
                                    "wrap": True
                                },
                                {
                                    "type": "TextBlock",
                                    "text": title,
                                    "weight": "Bolder",
                                    "size": "Large",
                                    "wrap": True
                                },
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "auto",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "🎯 For SAP Architects · BTP Developers · Functional Consultants · Transformation Leads",
                                                    "isSubtle": True,
                                                    "size": "Small",
                                                    "wrap": True
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        # Divider
                        {
                            "type": "TextBlock",
                            "text": "─────────────────────────────────────────",
                            "isSubtle": True,
                            "size": "Small"
                        },
                        # Article body
                        {
                            "type": "TextBlock",
                            "text": article,
                            "wrap": True,
                            "spacing": "Medium"
                        },
                        # Footer
                        {
                            "type": "TextBlock",
                            "text": "─────────────────────────────────────────",
                            "isSubtle": True,
                            "size": "Small"
                        },
                        {
                            "type": "TextBlock",
                            "text": "🤖 Generated by SAP AI Weekly Agent · Powered by SAP AI Core + GPT-4o",
                            "isSubtle": True,
                            "size": "Small",
                            "wrap": True
                        }
                    ],
                    # Action buttons for feedback
                    "actions": [
                        {
                            "type": "Action.OpenUrl",
                            "title": "💬 Give Feedback",
                            "url": "https://forms.office.com"  # replace with your feedback form
                        },
                        {
                            "type": "Action.OpenUrl",
                            "title": "📚 SAP Discovery Center",
                            "url": "https://discovery-center.cloud.sap"
                        },
                        {
                            "type": "Action.OpenUrl",
                            "title": "🔗 SAP AI Core Docs",
                            "url": "https://help.sap.com/docs/sap-ai-core"
                        }
                    ]
                }
            }
        ]
    }

    try:
        response = requests.post(
            webhook_url,
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=15
        )
        if response.status_code in (200, 202):
            return "✅ Article successfully posted to Teams channel!"
        else:
            return f"❌ Teams post failed: {response.status_code} — {response.text}"
    except Exception as e:
        return f"❌ Exception while posting to Teams: {str(e)}"
